# Generated by Django 4.2.2 on 2023-06-25 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=13)),
                ('profile_pic', models.ImageField(upload_to='profile/')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('Conf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference')),
                ('Speaker_id', models.ManyToManyField(to='speakers.speaker')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Names', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=100)),
                ('Phone', models.CharField(max_length=13)),
                ('Password', models.CharField(default=1234, max_length=10)),
                ('Payment', models.IntegerField(default=None)),
                ('Conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speakers.session')),
            ],
        ),
    ]
