# Generated by Django 4.2.2 on 2023-06-25 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Category', models.CharField(max_length=100)),
                ('Date', models.DateTimeField()),
                ('Venue', models.CharField(max_length=100)),
                ('Theme', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('Speaker', models.CharField(max_length=100)),
                ('Session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conferences.conference')),
            ],
        ),
    ]
